import { Settings } from "./settings/settings.component"
import { Session, sessionState } from "./svg/interfaces"

export const defaultSettings:Settings = {
  timer: {
    min: 2,
    sec: 0,
  },
  useParticipants: true,
  participants: [{include: true, name: 'Active Anna'}, {include: false, name: 'Inactive Ingrid'}],
  randomizeOrder: true,
}

export const defaultSession: Session = {
  state: sessionState.SETUP,
  timeLog: [],
  currentParticipant: 0,
  participants: [],
}

export const tardyNames = [
  "Tardy Toad",
  "Belated Bunny",
  "Delayed Deer",
  "Last-minute Lemur",
  "Languid Lizard",
  "Tardy Tortoise",
  "Dilatory Dolphin",
  "Sluggish Sloth",
  "Lagging Lynx",
  "Procrastinating Penguin",
  "Behindhand Badger",
  "Sluggardly Snail",
  "Latecomer Lion",
  "Lax Llama",
  "Delayed Dodo",
  "Tardy Tiger",
  "Behind-the-curve Bear",
  "Lagging Leopard",
  "Slowpoke Seahorse",
  "Belated Beetle",
  "Dilatory Duck",
  "Sluggish Squirrel",
  "Lethargic Lemming",
  "Last-minute Lark",
  "Tardy Toucan",
  "Delinquent Dog",
  "Slothful Sparrow",
  "Procrastinating Platypus",
  "Reluctant Raccoon",
  "Chatterbox Chimp",
  "Gabby Gazelle",
  "Gossiping Gecko",
  "Loquacious Lark",
  "Blabbering Bear",
  "Jabbering Jaguar",
  "Chatty Cheetah",
  "Rambunctious Robin",
  "Voluble Vulture",
  "Garrulous Goat",
  "Babbling Baboon",
  "Boisterous Bison",
  "Rambling Rabbit",
  "Jovial Jay",
  "Vocal Viper",
  "Patterning Parrot",
  "Buzzing Beetle",
  "Prattling Puma",
  "Garrulous Gopher",
  "Babbling Bullfrog",
  "Chirpy Chinchilla",
  "Rambunctious Rooster",
  "Loquacious Lemur",
  "Glib Guppy",
  "Prattle Partridge",
  "Yakkety Yak",
  "Blathering Beetle",
  "Bubbly Budgie"
]
